Module2 - 5
screamodev/.Net-homeworks pull request #10
Opened 2024-03-29 16:09 UTC by screamodev

2024-04-01 13:07 UTC, igorlopushko commented on module2HW5/module2HW5/Config/Actions.cs
> +namespace Homeworks.Module2HW1;
namespace має відповідати структурі папок. у даному випадку має бути:
`Homeworks.Module2HW1.Config`

Поміняй по всьому проекут

2024-04-01 13:11 UTC, igorlopushko commented on module2HW5/module2HW5/Models/LogType.cs
> +public enum LogType
Models це за звичай обʼєкти які бігають між рівнями, або приходять від клієнта. У даному випадку це Entity

2024-04-01 13:13 UTC, igorlopushko commented on module2HW5/module2HW5/Services/FileService.cs
> +    private readonly FileRepository _repository;
Сервіс має бути те, що обслуговує сутність. FileService обслуговує файл, для цього вже є репозиторій.

2024-04-01 13:13 UTC, igorlopushko commented on module2HW5/module2HW5/Config/Actions.cs
> +public class Actions
Виглядає як сервіс

2024-04-01 13:14 UTC, igorlopushko commented on module2HW5/module2HW5/Config/BusinessExceptions/SkippedLogicException.cs
> +public class SkippedLogicException : Exception
Папку з файлами по виключенями можна винести на верхній рівень

2024-04-01 13:15 UTC, igorlopushko commented on module2HW5/module2HW5/Config/LinkedList/LinkedList.cs
> +internal class LinkedList
все що стосується LinkedList можна винести на верхній рівень у папочку Data, без папки LinkedList

2024-04-01 13:16 UTC, igorlopushko requested changes
Треба переглянути структуру програми по коментарях

2024-04-02 08:43 UTC, screamodev commented on module2HW5/module2HW5/Services/FileService.cs
> +    private readonly FileRepository _repository;
т.е Сервис здесь лишний и можно напрямую репозиторий юзать?

2024-04-04 13:58 UTC, igorlopushko approved these changes

2024-04-05 07:14 UTC, merged